{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "externalapi.fullname" . }}-qa-configmap
data:
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  SECRET_PATH: "/app/secrets/neptuneExternalAPISecrets"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
{{ end }}
