services:
  neptune.api:
    image: neptune/api
    build:
      context: ..
      dockerfile: Neptune.API/Dockerfile

  neptune.externalapi:
    image: neptune/externalapi
    build:
      context: ..
      dockerfile: Neptune.ExternalAPI/Dockerfile

  neptune.gdalapi:
    image: neptune/gdalapi
    build:
      context: ..
      dockerfile: Neptune.GDALAPI/Dockerfile
